<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_login-formsignup</name>
   <tag></tag>
   <elementGuidId>ca61fb09-d46c-4cdc-ad6e-c78097d59c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form:signup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2d3a478-ad7b-444f-a0d9-c4e99eacee88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form:signup</value>
      <webElementGuid>75fa5db9-5bbf-4bac-a1ff-7cc97d16be0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>284dc276-9144-4323-af0c-7eced2b05f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/signup.gif;jsessionid=0DDC1D1AB5E77812A587B87284198A93</value>
      <webElementGuid>d6796390-c6b8-4659-80d5-eb576251cbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-form:signup</value>
      <webElementGuid>737279bd-fdb1-4ef5-ba66-0c6060b44860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>bbfd7c09-267e-4dc0-bc77-d0cff767c6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbutton</value>
      <webElementGuid>3ae66a90-4f64-4a54-8461-2971e8a9679f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form:signup&quot;)</value>
      <webElementGuid>bbd26a6e-281b-49ab-95fe-b25ff10217c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form:signup']</value>
      <webElementGuid>11d69be3-1ad3-45f1-9608-5c3ee28f0aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]/input[4]</value>
      <webElementGuid>db19b1c9-03da-4436-9172-450efc442197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>84cbea67-e1de-48ac-88f5-9a8851f89da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-form:signup' and @type = 'image' and @src = 'images/signup.gif;jsessionid=0DDC1D1AB5E77812A587B87284198A93' and @name = 'login-form:signup' and @alt = 'Signup']</value>
      <webElementGuid>e392fe55-7ace-4553-9d41-ed4aea66778a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
