<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_login-formlogin</name>
   <tag></tag>
   <elementGuidId>d1a1cb88-0813-4b6c-bcb8-9609b5a8ef0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form:login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb67d788-ce2b-49dc-b63d-002692fece83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form:login</value>
      <webElementGuid>993f033a-3b11-4fdd-9665-56b72b4c26f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>6ece6eeb-33c2-4d45-a35f-6efc83651b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/login.gif;jsessionid=3168FB50B98109A9E24BDD3E42CC7D97</value>
      <webElementGuid>8879baf2-f9db-412a-9272-9f7418a7371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-form:login</value>
      <webElementGuid>45e6f32d-5008-499f-be0b-b8c50b4e2364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3d5099a1-987b-4093-81cd-9f2726f9a07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbutton</value>
      <webElementGuid>943be817-7d17-4651-a444-3cc842bd086b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form:login&quot;)</value>
      <webElementGuid>3b544c92-1f63-424f-b5e0-86dd84a820ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form:login']</value>
      <webElementGuid>3aa8a00c-1a45-4cc1-b2df-4bd40af23374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]/input[3]</value>
      <webElementGuid>d6b0af63-e09f-41ed-bec3-996ecf039bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>7b7565a8-f20c-434b-bca7-464006e2c012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-form:login' and @type = 'image' and @src = 'images/login.gif;jsessionid=3168FB50B98109A9E24BDD3E42CC7D97' and @name = 'login-form:login' and @alt = 'Login']</value>
      <webElementGuid>c913ad07-4956-4eaf-9c05-b7a2bd7777d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
